
import { Dimensions, Platform } from 'react-native';

const constants = {
    LIGHT_BORDER: '#CBCCCF',
    BOX_SHADOW: 1,
    INPUT_TEXT_RADIUS: 5,
    LIGHT_BLUE: '#2F66A7',
    BACKGROUND_1: '#F1F2F8',
    RIPPLE_COLOR: '#9B9DF2',
    LINE_COLOR: '#CFD0D3',
    FONT_SAMSUNG_LIGHT: Platform.OS === 'android' ? 'samsung_s_sharp' : 'System',
    FONT_SAMSUNG_BOLD:
        Platform.OS === 'android' ? 'SamsungSharpSans-Bold' : 'System',
    FONT_HELVET_LIGHT:
        Platform.OS === 'android' ? 'HelveticaNeueLTCom-Md' : 'System',
    FONT_HELVET_BOLD:
        Platform.OS === 'android' ? 'HelveticaLTStd-Bold' : 'System',
    SMALL_FONT: 10,
    SMALLEST_FONT: 10,
    MEDIUM_FONT: 20,
    CATEGORIES: [
        { title: 'Pillar' },
        { title: 'Bumper' },
        { title: 'Decklid' },
        { title: 'Anti-intrusion bar' },
        { title: 'Roof rack' },
        { title: 'Fender' },
        { title: 'Sunroof Glass' },
        { title: 'Speaker' },
        { title: 'Dashcam' },
        { title: 'Ammeter' },
        { title: 'Ignition box' },
        { title: 'Ignition coil' },
    ],
    POST_DUMMAY: [
        { title: 'category' },
        { title: 'category' },
        { title: 'category' },
        { title: 'category' },
        { title: 'category' },
        { title: 'category' },
        { title: 'category' },
        { title: 'category' },
    ],
    INTRESTES_LIST: [
        { title: 'category' },
        { title: 'category' },
        { title: 'category' },
        { title: 'category' },
        { title: 'category' },
        { title: 'category' },
        { title: 'category' },
        { title: 'category' },
        { title: 'category' },
        { title: 'category' },
        { title: 'category' },
        { title: 'category' },
    ],
    USER_LIST: [
        { title: 'Zain' },
        { title: 'Faraz' },
        { title: 'arsalan' },
        { title: 'ammad' },
        { title: 'tanveer' },
        { title: 'omer' },
        { title: 'arshaq' },
        { title: 'owais' },
    ],
    CHAT_MESSAGES: [
        { id: 1, message: 'start' },
        { id: 2, message: 'hye aasd asd asd asd asd asdas dll' },
        { id: 1, message: 'hye all' },
        { id: 2, message: 'hye allasda sda sdas dasd asd asd' },
        { id: 1, message: 'hye all' },
        { id: 2, message: 'hye as dasd asasd as' },
        { id: 1, message: 'hye aasd ll' },
        { id: 2, message: 'hye all' },
        { id: 1, message: 'hye alasd asd l' },
        { id: 2, message: 'hye alla sda sd' },
        { id: 1, message: 'hye aasd asdll' },
        { id: 2, message: 'hye all' },
        { id: 1, message: 'hye aasd asd ll' },
        { id: 2, message: 'hye all' },
        { id: 1, message: 'hye asd asall' },
        { id: 2, message: 'hye aasd asd ll' },
        { id: 1, message: 'hye all' },
        { id: 2, message: 'hye all' },
        { id: 1, message: 'hye all' },
        { id: 2, message: 'hye alasd asdl' },
        { id: 1, message: 'hye all' },
        { id: 2, message: 'hye all' },
        { id: 1, message: 'hye aasd asll' },
        { id: 2, message: 'End' },
    ],
    MY_POSTS: [
        { title: 'My Post' },
        { title: 'My Post' },
        { title: 'My Post' },
        { title: 'My Post' },
        { title: 'My Post' },
        { title: 'My Post' },
        { title: 'My Post' },
        { title: 'My Post' },
        { title: 'My Post' },
        { title: 'My Post' },
        { title: 'My Post' },
        { title: 'My Post' },
        { title: 'My Post' },
        { title: 'My Post' },
    ]
}
export default constants